services:
  # A web service for the AI Debugger Factory
  - type: web
    name: ai-debugger-factory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgres://postgres:postgres@localhost:5432/ai_debugger_factory
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/v1/health

    # Update your render.yaml:
envVars:
  - key: OPENAI_API_KEY
    sync: false  # Set in Render dashboard
  - key: DATABASE_URL
    value: postgres://...
